import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import NavBar from "@/components/NavBar";
import Footer from "@/components/landing/Footer";

const inter = Inter({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark, cssLayerName: "clerk" }}>
      <html lang="en" className="light">
        <body className={`${inter.className}  antialiased`}>
          <main className=" bg-background">
            <NavBar />
            {children}
            <Footer/>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
