export default function Page() {
  return (
    <div className="max-w-7xl mx-auto pt-40 max-sm:pt-24 px-6  ">
      <div className=" px-6 py-14 max-sm:py-8 border border-muted-foreground rounded-xl inset-shadow-custom flex flex-col gap-6 bg-gradient-to-br from-gradient-start/10 via-gradient-via/10 to-gradient-end/10">
        <h1 className=" text-4xl max-sm:text-2xl font-semibold">
          Terms and Conditions
        </h1>
        <p>
          Welcome to 1BeatClub. By accessing our website and using our services,
          you agree to the following terms:
        </p>
      </div>
      <div className=" mt-12 space-y-8">
        <p className="mb-6">Last Updated: 10-10-2025</p>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">
            Acceptance of Terms
          </h2>
          <p>
            By accessing and using 1Beatclub, you accept and agree to be bound
            by the terms and provision of this agreement.
          </p>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">
            Description of Service
          </h2>
          <p>
            1Beatclub allows users to create and join clubs, add songs, vote on
            playlists, and share QR-based invitations to enjoy music together.
            We may update, enhance, or modify features at any time to improve
            your experience.
          </p>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">
            User Responsibilities
          </h2>
          <p>As a user of 1Beatclub, you agree to:</p>
          <ul className=" list-disc list-inside">
            <li>Provide accurate information when creating an account</li>
            <li>Maintain the confidentiality of your login credentials</li>
            <li>Use the platform only for lawful and respectful purposes</li>
            <li>
              Refrain from uploading or sharing inappropriate or copyrighted
              material
            </li>
            <li>
              Not interfere with or attempt to disrupt our services or network
            </li>
          </ul>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">
            Content Ownership and Usage
          </h2>
          <p>
            You retain ownership of the content (such as playlists, comments,
            and song suggestions) you create on 1Beatclub. By submitting
            content, you grant us a limited license to display and share it
            within the platform to provide our services.
          </p>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">
            Community Guidelines
          </h2>
          <p>
            We encourage creativity and fun but expect respect. Users are
            prohibited from posting or sharing:
          </p>
          <ul className=" list-disc list-inside">
            <li>
              <strong>Harmful or offensive content:</strong> Including hate
              speech, harassment, or threats
            </li>
            <li>
              <strong>Illegal material:</strong> Any content that violates local
              or international laws
            </li>
            <li>
              <strong>Copyrighted content:</strong> Songs or media without
              proper rights or permissions
            </li>
            <li>
              <strong>Spam or disruptive behavior:</strong> Including mass
              invites or fake accounts
            </li>
          </ul>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">
            AI-Powered Features
          </h2>
          <p>
            1Beatclub may include AI-driven features such as smart song
            recommendations or automated club insights. These tools are designed
            to enhance your experience but may not always produce perfect
            results. We are not responsible for any inaccuracies generated by
            AI.
          </p>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">Privacy</h2>
          <p>
            Your privacy is important to us. Please review our{" "}
            <a href="/privacy" className=" underline">
              Privacy Policy
            </a>{" "}
            to understand how we collect, store, and use your data, including
            information related to your clubs, songs, and preferences.
          </p>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">
            Termination of Use
          </h2>
          <p>
            We reserve the right to suspend or terminate your account at any
            time, without notice, if we believe you have violated these terms or
            engaged in misuse of the platform.
          </p>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">
            Limitation of Liability
          </h2>
          <p>
            1Beatclub is provided “as is.” We make no guarantees regarding
            uptime, performance, or the availability of specific features. We
            are not liable for any indirect or consequential damages arising
            from your use of the service.
          </p>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">
            Modifications to Terms
          </h2>
          <p>
            We may update these terms from time to time to reflect changes in
            our practices or services. Updates will be posted on this page with
            a revised “Last Updated” date.
          </p>
        </div>
        <div className=" space-y-2">
          <h2 className=" text-2xl max-sm:text-lg font-semibold">Contact</h2>
          <p>
            If you have any questions about these Terms of Service, please reach
            out to us via our{" "}
            <a href="/contact" className=" underline">
              Contact Page
            </a>
            .
          </p>
        </div>
      </div>
    </div>
  );
}
